export default {
  windowEl: window,
  documentEl: document,
  htmlEl: document.documentElement,
  bodyEl: document.body,
  bannerSlider: document.querySelector(".banner-slider"),
  marketing: document.querySelector(".marketing"),
  catalogSlider: document.querySelector(".hero-catalog__slider"),
  catalogFiltersTop: document.querySelectorAll(".catalog-filter__top"),
  hideFilters: document.querySelector(".hide-filters"),
  catalogColumns: document.querySelector(".catalog-columns__list"),
  catalogGridContent: document.querySelector(".catalog-grid__content"),
  catalogFilterItems: document.querySelectorAll(".catalog-filter__item"),
  catalogChoise: document.querySelector(".catalog-choice"),
  customSelect: document.querySelectorAll(".custom-select"),
  freeDeliveryBtn: document.querySelector(".free-delivery__btn"),
  colorSelectSelected: document.querySelector(".color-select__selected"),
  colorSelect: document.querySelector(".color-select"),
  sizeSelect: document.querySelector(".size-select"),
  stepper: document.querySelector(".stepper"),
  cardSliderThumbs: document.querySelector(".card-slider__thumbs"),
  sliderImg: document.querySelector(".card-slider__main img"),
  cardDescLink: document.querySelectorAll(".card-desc__link"),
  cardRelatedSlider: document.querySelector(".card-related__slider"),
};
